#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kursovaya")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertpatients(patients instance);
    partial void Updatepatients(patients instance);
    partial void Deletepatients(patients instance);
    partial void Insertdischargedpatient(dischargedpatient instance);
    partial void Updatedischargedpatient(dischargedpatient instance);
    partial void Deletedischargedpatient(dischargedpatient instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::kursovaya.Properties.Settings.Default.kursovayaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<patients> patients
		{
			get
			{
				return this.GetTable<patients>();
			}
		}
		
		public System.Data.Linq.Table<dischargedpatient> dischargedpatient
		{
			get
			{
				return this.GetTable<dischargedpatient>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.patients")]
	public partial class patients : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _FIO;
		
		private System.Nullable<System.DateTime> _birthdate;
		
		private System.Nullable<System.DateTime> _admissiondate;
		
		private string _diagnosis;
		
		private string _medicine;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFIOChanging(string value);
    partial void OnFIOChanged();
    partial void OnbirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdateChanged();
    partial void OnadmissiondateChanging(System.Nullable<System.DateTime> value);
    partial void OnadmissiondateChanged();
    partial void OndiagnosisChanging(string value);
    partial void OndiagnosisChanged();
    partial void OnmedicineChanging(string value);
    partial void OnmedicineChanged();
    #endregion
		
		public patients()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="NVarChar(100)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this.OnFIOChanging(value);
					this.SendPropertyChanging();
					this._FIO = value;
					this.SendPropertyChanged("FIO");
					this.OnFIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this.OnbirthdateChanging(value);
					this.SendPropertyChanging();
					this._birthdate = value;
					this.SendPropertyChanged("birthdate");
					this.OnbirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissiondate", DbType="DateTime")]
		public System.Nullable<System.DateTime> admissiondate
		{
			get
			{
				return this._admissiondate;
			}
			set
			{
				if ((this._admissiondate != value))
				{
					this.OnadmissiondateChanging(value);
					this.SendPropertyChanging();
					this._admissiondate = value;
					this.SendPropertyChanged("admissiondate");
					this.OnadmissiondateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(100)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this.OndiagnosisChanging(value);
					this.SendPropertyChanging();
					this._diagnosis = value;
					this.SendPropertyChanged("diagnosis");
					this.OndiagnosisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medicine", DbType="NVarChar(100)")]
		public string medicine
		{
			get
			{
				return this._medicine;
			}
			set
			{
				if ((this._medicine != value))
				{
					this.OnmedicineChanging(value);
					this.SendPropertyChanging();
					this._medicine = value;
					this.SendPropertyChanged("medicine");
					this.OnmedicineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dischargedpatient")]
	public partial class dischargedpatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _FIO;
		
		private System.Nullable<System.DateTime> _birthdate;
		
		private System.Nullable<System.DateTime> _admissiondate;
		
		private System.Nullable<System.DateTime> _dischargedate;
		
		private string _diagnosis;
		
		private string _medicine;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFIOChanging(string value);
    partial void OnFIOChanged();
    partial void OnbirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdateChanged();
    partial void OnadmissiondateChanging(System.Nullable<System.DateTime> value);
    partial void OnadmissiondateChanged();
    partial void OndischargedateChanging(System.Nullable<System.DateTime> value);
    partial void OndischargedateChanged();
    partial void OndiagnosisChanging(string value);
    partial void OndiagnosisChanged();
    partial void OnmedicineChanging(string value);
    partial void OnmedicineChanged();
    #endregion
		
		public dischargedpatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="NVarChar(100)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this.OnFIOChanging(value);
					this.SendPropertyChanging();
					this._FIO = value;
					this.SendPropertyChanged("FIO");
					this.OnFIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this.OnbirthdateChanging(value);
					this.SendPropertyChanging();
					this._birthdate = value;
					this.SendPropertyChanged("birthdate");
					this.OnbirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissiondate", DbType="DateTime")]
		public System.Nullable<System.DateTime> admissiondate
		{
			get
			{
				return this._admissiondate;
			}
			set
			{
				if ((this._admissiondate != value))
				{
					this.OnadmissiondateChanging(value);
					this.SendPropertyChanging();
					this._admissiondate = value;
					this.SendPropertyChanged("admissiondate");
					this.OnadmissiondateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dischargedate
		{
			get
			{
				return this._dischargedate;
			}
			set
			{
				if ((this._dischargedate != value))
				{
					this.OndischargedateChanging(value);
					this.SendPropertyChanging();
					this._dischargedate = value;
					this.SendPropertyChanged("dischargedate");
					this.OndischargedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(100)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this.OndiagnosisChanging(value);
					this.SendPropertyChanging();
					this._diagnosis = value;
					this.SendPropertyChanged("diagnosis");
					this.OndiagnosisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medicine", DbType="NVarChar(100)")]
		public string medicine
		{
			get
			{
				return this._medicine;
			}
			set
			{
				if ((this._medicine != value))
				{
					this.OnmedicineChanging(value);
					this.SendPropertyChanging();
					this._medicine = value;
					this.SendPropertyChanged("medicine");
					this.OnmedicineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
